name: Notify Discord on Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  discord_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send PR notification to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\": \"🔔 New Pull Request: [${{ github.event.pull_request.title }}](${{ github.event.pull_request.html_url }}) by ${{ github.actor }}\"}" \
          $DISCORD_WEBHOOK
